USE [master]
GO
/****** Object:  Database [INVENTARIOTI]    Script Date: 12/09/2023 02:39:26 ******/
CREATE DATABASE [INVENTARIOTI] ON  PRIMARY 
( NAME = N'INVENTARIOTI', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\INVENTARIOTI.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'INVENTARIOTI_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\INVENTARIOTI_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [INVENTARIOTI] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [INVENTARIOTI].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [INVENTARIOTI] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [INVENTARIOTI] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [INVENTARIOTI] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [INVENTARIOTI] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [INVENTARIOTI] SET ARITHABORT OFF 
GO
ALTER DATABASE [INVENTARIOTI] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [INVENTARIOTI] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [INVENTARIOTI] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [INVENTARIOTI] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [INVENTARIOTI] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [INVENTARIOTI] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [INVENTARIOTI] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [INVENTARIOTI] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [INVENTARIOTI] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [INVENTARIOTI] SET  DISABLE_BROKER 
GO
ALTER DATABASE [INVENTARIOTI] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [INVENTARIOTI] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [INVENTARIOTI] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [INVENTARIOTI] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [INVENTARIOTI] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [INVENTARIOTI] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [INVENTARIOTI] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [INVENTARIOTI] SET RECOVERY FULL 
GO
ALTER DATABASE [INVENTARIOTI] SET  MULTI_USER 
GO
ALTER DATABASE [INVENTARIOTI] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [INVENTARIOTI] SET DB_CHAINING OFF 
GO
EXEC sys.sp_db_vardecimal_storage_format N'INVENTARIOTI', N'ON'
GO
USE [INVENTARIOTI]
GO
/****** Object:  Table [dbo].[AUX_EQUIPAMENTO_LICENCA]    Script Date: 12/09/2023 02:39:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AUX_EQUIPAMENTO_LICENCA](
	[Auto_Codigo] [int] IDENTITY(1,1) NOT NULL,
	[Auto_Codigo_Software] [int] NULL,
	[Auto_Codigo_Software_Licenca] [int] NULL,
	[Auto_Codigo_Equipamento] [int] NULL,
	[Data] [datetime] NULL,
	[Observacao] [varchar](200) NULL,
 CONSTRAINT [PK_AUX_EQUIPAMENTO_LICENCA] PRIMARY KEY CLUSTERED 
(
	[Auto_Codigo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Equipamento]    Script Date: 12/09/2023 02:39:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Equipamento](
	[Auto_Codigo] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](200) NULL,
	[Tipo_Aquisicao] [varchar](30) NULL,
	[Data_Compra] [datetime] NULL,
	[Data_Garantia] [datetime] NULL,
	[Setor] [varchar](120) NULL,
	[Marca] [varchar](50) NULL,
	[Observacao] [varchar](200) NULL,
	[Status] [varchar](30) NULL,
 CONSTRAINT [PK_Equipamento] PRIMARY KEY CLUSTERED 
(
	[Auto_Codigo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SOFTWARE]    Script Date: 12/09/2023 02:39:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SOFTWARE](
	[Auto_Codigo] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](200) NULL,
	[Tipo_Software] [varchar](50) NULL,
	[Tipo_Licenca] [varchar](30) NULL,
	[Marca] [varchar](50) NULL,
	[Observacao] [varchar](200) NULL,
	[Status] [varchar](30) NULL,
 CONSTRAINT [PK_SOFTWARE] PRIMARY KEY CLUSTERED 
(
	[Auto_Codigo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SOFTWARE_LICENCA]    Script Date: 12/09/2023 02:39:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SOFTWARE_LICENCA](
	[Auto_Codigo] [int] IDENTITY(1,1) NOT NULL,
	[Auto_Codigo_Software] [int] NULL,
	[Nome] [varchar](200) NULL,
	[Chave] [varchar](100) NULL,
	[Data_Compra] [datetime] NULL,
	[Data_Suporte] [datetime] NULL,
	[Observacao] [varchar](200) NULL,
	[Status] [varchar](30) NULL,
 CONSTRAINT [PK_SOFTWARE_LICENCA] PRIMARY KEY CLUSTERED 
(
	[Auto_Codigo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[AUX_EQUIPAMENTO_LICENCA] ON 
GO
INSERT [dbo].[AUX_EQUIPAMENTO_LICENCA] ([Auto_Codigo], [Auto_Codigo_Software], [Auto_Codigo_Software_Licenca], [Auto_Codigo_Equipamento], [Data], [Observacao]) VALUES (6, 3, 3, 2, NULL, NULL)
GO
INSERT [dbo].[AUX_EQUIPAMENTO_LICENCA] ([Auto_Codigo], [Auto_Codigo_Software], [Auto_Codigo_Software_Licenca], [Auto_Codigo_Equipamento], [Data], [Observacao]) VALUES (7, 2, 2, 1, NULL, NULL)
GO
SET IDENTITY_INSERT [dbo].[AUX_EQUIPAMENTO_LICENCA] OFF
GO
SET IDENTITY_INSERT [dbo].[Equipamento] ON 
GO
INSERT [dbo].[Equipamento] ([Auto_Codigo], [Nome], [Tipo_Aquisicao], [Data_Compra], [Data_Garantia], [Setor], [Marca], [Observacao], [Status]) VALUES (1, N'Equipamento Servidor R710AAB', N'Novo', CAST(N'2023-08-09T00:00:00.000' AS DateTime), CAST(N'2023-08-31T00:00:00.000' AS DateTime), N'Produção', N'Dell', N'Computador Novo', N'Ativo')
GO
INSERT [dbo].[Equipamento] ([Auto_Codigo], [Nome], [Tipo_Aquisicao], [Data_Compra], [Data_Garantia], [Setor], [Marca], [Observacao], [Status]) VALUES (2, N'Computador Vendas', N'Novo', CAST(N'2023-08-08T00:00:00.000' AS DateTime), CAST(N'2024-08-08T00:00:00.000' AS DateTime), N'Vendas', N'Lenovo', N'Computador com Garantia mas é Semi novo
', N'Ativo')
GO
SET IDENTITY_INSERT [dbo].[Equipamento] OFF
GO
SET IDENTITY_INSERT [dbo].[SOFTWARE] ON 
GO
INSERT [dbo].[SOFTWARE] ([Auto_Codigo], [Nome], [Tipo_Software], [Tipo_Licenca], [Marca], [Observacao], [Status]) VALUES (2, N'Windows 2019 Server Standard', N'Sistema Operacional', N'Chave', N'Microsoft', N'', N'Ativo')
GO
INSERT [dbo].[SOFTWARE] ([Auto_Codigo], [Nome], [Tipo_Software], [Tipo_Licenca], [Marca], [Observacao], [Status]) VALUES (3, N'Office 2019', N'Office', N'Chave', N'Microsoft', NULL, N'Ativo')
GO
SET IDENTITY_INSERT [dbo].[SOFTWARE] OFF
GO
SET IDENTITY_INSERT [dbo].[SOFTWARE_LICENCA] ON 
GO
INSERT [dbo].[SOFTWARE_LICENCA] ([Auto_Codigo], [Auto_Codigo_Software], [Nome], [Chave], [Data_Compra], [Data_Suporte], [Observacao], [Status]) VALUES (2, 2, N'Windows 2019 Server Standard', N'AAAG-AAAA-DDDD-0000', CAST(N'2023-08-08T00:00:00.000' AS DateTime), CAST(N'2024-08-08T00:00:00.000' AS DateTime), NULL, N'Ativo')
GO
INSERT [dbo].[SOFTWARE_LICENCA] ([Auto_Codigo], [Auto_Codigo_Software], [Nome], [Chave], [Data_Compra], [Data_Suporte], [Observacao], [Status]) VALUES (3, 3, N'Office 2019', N'0000-AAAA-DDDDD-11111-2', CAST(N'2023-08-08T00:00:00.000' AS DateTime), CAST(N'2023-09-08T00:00:00.000' AS DateTime), NULL, N'Ativo')
GO
SET IDENTITY_INSERT [dbo].[SOFTWARE_LICENCA] OFF
GO
USE [master]
GO
ALTER DATABASE [INVENTARIOTI] SET  READ_WRITE 
GO
